#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_11 //MCLK
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_43  //LRCK
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_12 //SCLK
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_13 //DOUT
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_44  //DIN

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_NC
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_9
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_10
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR

#define BUILTIN_LED_GPIO        GPIO_NUM_48
#define BOOT_BUTTON_GPIO        GPIO_NUM_6

#define DISPLAY_OLED_WIDTH   128
#define DISPLAY_OLED_HEIGHT  64


#define I2C_BUS     I2C_NUM_0


#endif // _BOARD_CONFIG_H_
